[general]
import = ["~/.config/alacritty/theme.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14

# Fixes the annoying small strip of blank space at the bottom of Alacritty's
# window.
[font.offset]
x = 0
y = 1

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
option_as_alt = "Both"
decorations = "None"

# Use as much screen real estate as possible.
[window.padding]
x = 0
y = 0

# Start up and/or attach to the the `main` session when opening Alacritty.
[terminal.shell]
program = "/opt/homebrew/bin/nu"
args = [
  # Start as a login shell.
  "-l",
  # Source the configuration files correctly.
  "--config",
  "~/.config/nushell/config.nu",
  "--env-config",
  "~/.config/nushell/env.nu",
  # Attach to tmux's 'home' session.
  # In fact, this is the only responsibility of this shell.
  "-c",
  "/opt/homebrew/bin/tmux new-session -A -s home -c ~/",
]
