[general]
import = ["~/.config/alacritty/_active_theme.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14

# Fixes the annoying small strip of blank space at the bottom of Alacritty's
# window.
[font.offset]
x = 0
y = -1

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "Buttonless"
option_as_alt = "Both"

# Use as much screen real estate as possible.
[window.padding]
x = 0
y = 1

# Start up and/or attach to the the `home` session when opening Alacritty.
[terminal.shell]
program = "/bin/zsh"
args = [
  # Start as a login shell.
  "-l",
  # Attach to tmux's 'home' session.
  # In fact, this is the only responsibility of this shell.
  "-c",
  "/opt/homebrew/bin/tmux new-session -A -s home -c ~/",
]
