# All credit goes to the maintainers of the
# `https://github.com/alacritty/alacritty-theme` project.

# Catppuccin Frappe theme.

[colors.primary] # Default colors.
background = '#303446'        # base
foreground = '#C6D0F5'        # text
# Bright and dim foreground colors.
dim_foreground = '#C6D0F5'    # text
bright_foreground = '#C6D0F5' # text

[colors.cursor] # Cursor colors.
text = '#303446'              # base
cursor = '#F2D5CF'            # rosewater

[colors.vi_mode_cursor]
text = '#303446'              # base
cursor = '#BABBF1'            # lavender

[colors.search.matches] # Search colors.
foreground = '#303446'        # base
background = '#A5ADCE'        # subtext0
[colors.search.focused_match]
foreground = '#303446'        # base
background = '#A6D189'        # green
[colors.footer_bar]
foreground = '#303446'        # base
background = '#A5ADCE'        # subtext0

[colors.hints.start] # Keyboard regex hints.
foreground = '#303446'        # base
background = '#E5C890'        # yellow
[colors.hints.end]
foreground = '#303446'        # base
background = '#A5ADCE'        # subtext0

[colors.selection] # Selection colors.
text = '#303446'              # base
background = '#F2D5CF'        # rosewater

[colors.normal] # Normal colors.
black = '#51576D'             # surface1
red = '#E78284'               # red
green = '#A6D189'             # green
yellow = '#E5C890'            # yellow
blue = '#8CAAEE'              # blue
magenta = '#F4B8E4'           # pink
cyan = '#81C8BE'              # teal
white = '#B5BFE2'             # subtext1

[colors.bright] # Bright colors.
black = '#626880'             # surface2
red = '#E78284'               # red
green = '#A6D189'             # green
yellow = '#E5C890'            # yellow
blue = '#8CAAEE'              # blue
magenta = '#F4B8E4'           # pink
cyan = '#81C8BE'              # teal
white = '#A5ADCE'             # subtext0

[colors.dim] # Dim colors.
black = '#51576D'             # surface1
red = '#E78284'               # red
green = '#A6D189'             # green
yellow = '#E5C890'            # yellow
blue = '#8CAAEE'              # blue
magenta = '#F4B8E4'           # pink
cyan = '#81C8BE'              # teal
white = '#B5BFE2'             # subtext1
