# Ref: https://nikitabobko.github.io/AeroSpace/guide

# Start AeroSpace at login.
start-at-login = true

# Activate border highlighting.
after-startup-command = [
  'exec-and-forget borders active_color=0xffffd800 inactive_color=0xff494d64 width=8.0',
]

# Normalizations. Ref: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Ref: https://nikitabobko.github.io/AeroSpace/guide#layouts
accordion-padding = 30

# Default layout. Options: tiles|accordion.
default-root-container-layout = 'tiles'

# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto' # horizontal|vertical|auto

# Effectively turn off macOS "Hide application" (Cmd-h) feature.
#   => No more accidental hiding of applications 😤
# Ref: https://nikitabobko.github.io/AeroSpace/guide#hide-applications
automatically-unhide-macos-hidden-apps = true

# Ref: https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 Ref: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 22
inner.vertical = 22
outer.left = 12
outer.bottom = 12
outer.top = 12
outer.right = 12


# Automatically assign applications to workspaces.

# Y - Google Chrome.
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace y'

# U - Alacritty.
[[on-window-detected]]
if.app-id = 'org.alacritty'
run = 'move-node-to-workspace u'

# I - Intellij.
[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = 'move-node-to-workspace i'

# O - Apple Mail & Slack.
[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = 'move-node-to-workspace o'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace o'

# P - Apple Calendar & Things.
[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = 'move-node-to-workspace p'

[[on-window-detected]]
if.app-id = 'com.culturedcode.ThingsMac'
run = 'move-node-to-workspace p'


# Ref: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.main.binding]
# Key pallette:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
#                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
#                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
#                   sectionSign (ISO keyboards only, european keyboards only)
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right
# Available modifiers: cmd, alt, ctrl, shift

# Commands ref: https://nikitabobko.github.io/AeroSpace/commands
# Exec ref: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget

# Ref: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'

# Submodes.
cmd-alt-ctrl-shift-w = 'mode windows'
cmd-alt-ctrl-shift-s = 'mode spaces'
cmd-alt-ctrl-shift-q = 'mode quick-aerospace-actions'
cmd-alt-ctrl-shift-a = 'mode applications'

[mode.windows.binding]
esc = 'mode main'

# Focus window nodes.
# Ref: https://nikitabobko.github.io/AeroSpace/commands#focus
h = ['focus left', 'mode main']
j = ['focus down', 'mode main']
k = ['focus up', 'mode main']
l = ['focus right', 'mode main']

# Move window nodes around.
# Ref: https://nikitabobko.github.io/AeroSpace/commands#move
shift-h = ['move left', 'mode main']
shift-j = ['move down', 'mode main']
shift-k = ['move up', 'mode main']
shift-l = ['move right', 'mode main']

# Join window nodes.
# Ref: https://nikitabobko.github.io/AeroSpace/commands#join-with
ctrl-h = ['join-with left', 'mode main']
ctrl-j = ['join-with down', 'mode main']
ctrl-k = ['join-with up', 'mode main']
ctrl-l = ['join-with right', 'mode main']

# Flatten layout and reset sizes.
f = ['flatten-workspace-tree', 'mode main']

# Close all windows but the current one.
backspace = ['close-all-windows-but-current', 'mode main']

# Resize window nodes.
# Ref: https://nikitabobko.github.io/AeroSpace/commands#resize
"minus" = 'resize smart -50'
"shift-equal" = 'resize smart +50'

[mode.spaces.binding]
esc = 'mode main'

# Focus workspaces.
# Ref: https://nikitabobko.github.io/AeroSpace/commands#workspace
y = ['workspace y', 'mode main']
u = ['workspace u', 'mode main']
i = ['workspace i', 'mode main']
o = ['workspace o', 'mode main']
p = ['workspace p', 'mode main']
h = ['workspace h', 'mode main']
j = ['workspace j', 'mode main']
k = ['workspace k', 'mode main']
l = ['workspace l', 'mode main']

# Move nodes to workspaces and subsequently focus them.
# Ref: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
shift-y = ['move-node-to-workspace y', 'workspace y', 'mode main']
shift-u = ['move-node-to-workspace u', 'workspace u', 'mode main']
shift-i = ['move-node-to-workspace i', 'workspace i', 'mode main']
shift-o = ['move-node-to-workspace o', 'workspace o', 'mode main']
shift-p = ['move-node-to-workspace p', 'workspace p', 'mode main']
shift-h = ['move-node-to-workspace h', 'workspace h', 'mode main']
shift-j = ['move-node-to-workspace j', 'workspace j', 'mode main']
shift-k = ['move-node-to-workspace k', 'workspace k', 'mode main']
shift-l = ['move-node-to-workspace l', 'workspace l', 'mode main']

# Ref: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
f = 'move-workspace-to-monitor --wrap-around next' # -> Move workspace [f]orward.

[mode.quick-aerospace-actions.binding]
esc = 'mode main'

# Switch layouts and toggle orientations.
# Ref: https://nikitabobko.github.io/AeroSpace/commands#layout
t = ['layout tiles horizontal vertical', 'mode main']
a = ['layout accordion horizontal vertical', 'mode main']

# Reload configuration.
r = ['reload-config', 'mode main']

[mode.applications.binding]
esc = 'mode main'

a = ['exec-and-forget open -a Alacritty', 'mode main']
b = ['exec-and-forget open -a Bear', 'mode main']
c = ['exec-and-forget open -a Calendar', 'mode main']
f = ['exec-and-forget open -a Finder', 'mode main']
g = ['exec-and-forget open -a "Google Chrome"', 'mode main']
i = ['exec-and-forget open -a "Intellij IDEA"', 'mode main']
m = ['exec-and-forget open -a Mail', 'mode main']
s = ['exec-and-forget open -a Slack', 'mode main']
t = ['exec-and-forget open -a Things3', 'mode main']
